# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMDIGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindowVertical = QtWidgets.QWidget()
        self.subwindowVertical.setObjectName("subwindowVertical")
        self.label = QtWidgets.QLabel(self.subwindowVertical)
        self.label.setGeometry(QtCore.QRect(60, 40, 47, 13))
        self.label.setObjectName("label")
        self.subwindowPie = QtWidgets.QWidget()
        self.subwindowPie.setObjectName("subwindowPie")
        self.label_2 = QtWidgets.QLabel(self.subwindowPie)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.subwindowHorizontal = QtWidgets.QWidget()
        self.subwindowHorizontal.setObjectName("subwindowHorizontal")
        self.groupBox = QtWidgets.QGroupBox(self.subwindowHorizontal)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 711, 241))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIP_Settings = QtWidgets.QAction(MainWindow)
        self.actionIP_Settings.setObjectName("actionIP_Settings")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuSettings.addAction(self.actionIP_Settings)
        self.menuSettings.addAction(self.actionSettings)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subwindowVertical.setWindowTitle(_translate("MainWindow", "Vertical Slice"))
        self.label.setText(_translate("MainWindow", "1111"))
        self.subwindowPie.setWindowTitle(_translate("MainWindow", "Pie Slice"))
        self.label_2.setText(_translate("MainWindow", "2222"))
        self.subwindowHorizontal.setWindowTitle(_translate("MainWindow", "Horizontal Slice"))
        self.groupBox.setTitle(_translate("MainWindow", "Horizontal Slice"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionIP_Settings.setText(_translate("MainWindow", "IP Settings"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
